### ISSUE TITLE
How to use goToAndStop() method

### ISSUE THREAD

**Issue by nicco88** [crello/react-lottie#10]
I'd like to be able to play the animation and stop it on a certain frame. 
Apparently the lottie-web library uses the goToAndStop() method to achieve that.
Do you guys know how to use it with react-lottie?
Thank you

**Comment by good-idea** [comment]
I just made a PR (#11) that allows this using a new prop `animationRef`. @crello take a look and let me know if it looks good to you!

**Comment by nicco88** [comment]
@good-idea sorry for the delay... I just got a look and it looks great to me!

**Comment by good-idea** [comment]
@nicco88 I made a separate branch that you can install directly --- i didn't want to publish my own fork --- you can use it with `npm install git+https://git@github.com/good-idea/react-lottie#installable`

**Comment by nicco88** [comment]
@good-idea Awesome, thank you so much for your help!

**Comment by lazysergey** [comment]
@good-idea @nicco88 guys, thanks for collaboration 👍 merged in `0.0.8`

**Comment by good-idea** [comment]
Thanks!
