### ISSUE TITLE
Lottie animation plays slowly on 2nd re-render and then not at all on 3rd re-render

### ISSUE THREAD

**Issue by l-irizarry** [crello/react-lottie#14]
Hey!

Firstly, thank you so much for forking from that other React library and creating this one. It works great!

In my React project, I have a Lottie component that I will show conditionally, so it'll be there for a while and then disappear, then appear again, etc, based on certain user actions. The first time I create this component, it's totally fine and plays normally. However, the second time I re-render it, the animation plays slowly at first for the first half and then normally for the second half. Finally, the third time, it won't even render and my browser freezes.

So I basically have:

let content;
if ( [condition] ) {
   content = <BasicLottieComponent />;
} else {
   content = [something else];
}

The second and third times that [condition] is true the issues I describe above happen.

Do you have any ideas as to what I could do to make sure that the animation always works? Do I need to "destroy" it after it disappears the first time? Or is it a cache issue?

Any help would be truly appreciated. Thanks!

**Comment by lazysergey** [comment]
hi mate here [I've created basic example]( https://stackblitz.com/edit/crello-react-lottie-basic?file=index.tsx) with toggle button which will mount/unmount animation component, I don't see any issues with subsequent remounting - it definitely takes some milliseconds to init animation, but I see no lagging after its loaded, can you please fork and reproduce the issue?

**Comment by l-irizarry** [comment]
Hey Sergey,

I re-implemented it using your code as an example and it now works for me. Thanks for the help!

**Comment by lazysergey** [comment]
@liriz002 awesome 👍
