### ISSUE TITLE
Error message in strict mode

### ISSUE THREAD

**Issue by yeungc** [crello/react-lottie#17]
Hello, below error message will showing up when using strict mode:
![Image](https://user-images.githubusercontent.com/7931068/79061694-436f7180-7cc5-11ea-9e29-94cf12427860.png)

May I know if that is possible to not use UNSAFE_componentWillUpdate? Thank you!

**Comment by capsudo** [comment]
It is meant to be refactored according to comment on this line : https://github.com/crello/react-lottie/blob/master/src/components/Lottie/index.tsx#L38

**Comment by yeungc** [comment]
> 
> 
> It is meant to be refactored according to comment on this line : https://github.com/crello/react-lottie/blob/master/src/components/Lottie/index.tsx#L38

Yes you are correct.

**Comment by nathanharper** [comment]
I made a pull request for this.

https://github.com/crello/react-lottie/pull/20

I basically just moved all the logic in `UNSAFE_componentWillUpdate` to `componentDidUpdate`, as recommended by the React docs. If you're aware of any issues this might raise, let me know, but the test site seemed to work identically. I would really like to get rid of this StrictMode error in our app, so let me know what else I can do! Thanks!

**Comment by yeungc** [comment]
This should fix the problem, just waiting for merge, going to close the issue now.

**Comment by telou** [comment]
This was closed as completed but it looks like [the PR](https://github.com/crello/react-lottie/pull/20) never got merged? Is there an update on this?

**Comment by nathanharper** [comment]
@telou this library seems to be unmaintained, you're probably best off forking it at this point.
