### ISSUE TITLE
Load JSON remotely

### ISSUE THREAD

**Issue by sliktrik** [crello/react-lottie#6]
is it possible to load the animation data remotely?
for example:

```
<Lottie
   options = {{
      animationData: "https://someurl.com/animationData.json",
      loop: true,
      autoplay: true,
   }}
   width = "1293px"
   height = "300px"
 />  
```

**Comment by lazysergey** [comment]
@sliktrik do you have public url with that json?

**Comment by lazysergey** [comment]
@sliktrik original lottie-web defines/accepts two types of configs: `AnimationConfigWithPath` and `AnimationConfigWithData`. Currently we support only `AnimationConfigWithData`, but after #7 you will be able to pass the path as below:

```typescript
<Lottie
   config = {{
      path: "https://raw.githubusercontent.com/airbnb/lottie-web/master/demo/gatin/data.json",
      loop: true,
      autoplay: true,
   }}
   width = "1293px"
   height = "300px"
 />  
```

ps: note that we use `config` not `options` as defined in original lottie-web

**Comment by sliktrik** [comment]
@lazysergey thank you!

**Comment by lazysergey** [comment]
@sliktrik check out 0.0.6

**Comment by rndD** [comment]
Can we count it as a close one? =)
