### ISSUE TITLE
Integration with Gatsby

### ISSUE THREAD

**Issue by luizcieslak** [crello/react-lottie#9]
Hi guys. Thanks for keeping the lib updated!

Did you manage to make it work with Gatsby? I read that is kind of an old issue https://github.com/chenqingspring/react-lottie/issues/42. Been trying to replicate the solution here but no success so far.

I'm able to help if needed.

**Comment by lazysergey** [comment]
@luizcieslak  hi mate, feel free to create PR with Gatsby support 👍

**Comment by nicco88** [comment]
@luizcieslak I'm currently using it with Gatsby, and the animation works on my repo. Are you having any errors?

**Comment by luizcieslak** [comment]
yes @nicco88, I had some errors related to webpack. Could you point me your repo?

**Comment by nicco88** [comment]
@luizcieslak unfortunately the code is my company's private repo, so I'm not able to share it with you.
So are you having errors in the build phase? Do you see any animations in development?

**Comment by ehudsn** [comment]
I seemed to have fixed my issues by removing the videos the animator had put in the project, bringing the data.json file from 50k+ lines to under 1000. Everything is working as expected now. @luizcieslak did you ever figure out your issue?

**Comment by luizcieslak** [comment]
Hi guys! I tested it again now and couldn't reproduce this issue anymore. Probably it was something not related to this lib. Thanks for the help!
